services:
  mongodb:
    image: mongo:7.0
    container_name: my_sms_mongodb_dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: my_sms_dev
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - app-network

  backend:
    build: 
      context: ./my_sms_be
      dockerfile: Dockerfile.dev
    container_name: my_sms_be_dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/my_sms_dev?authSource=admin
      - BUNDLE_PATH=/usr/local/bundle
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
    depends_on:
      - mongodb
    volumes:
      - ./my_sms_be:/rails
      - bundle_cache:/usr/local/bundle
      - /rails/tmp
      - /rails/log
    networks:
      - app-network

  frontend:
    build:
      context: ./my_sms_fe
      dockerfile: Dockerfile.dev
    container_name: my_sms_fe_dev
    restart: unless-stopped
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./my_sms_fe:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  mongodb_dev_data:
  bundle_cache:

networks:
  app-network:
    driver: bridge