source "https://rubygems.org"

ruby "3.4.4"

gem "rails", "~> 7.1.0"
gem "puma", ">= 5.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "bootsnap", require: false
gem "rack-cors"
gem "mongoid"
gem "twilio-ruby"
gem "jwt"
gem "bcrypt"
gem "ostruct"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem 'rspec-rails'
  gem 'webmock'        
  gem 'factory_bot_rails'
end