
development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://admin:password123@mongodb:27017/my_sms_dev?authSource=admin' %>
      options:
        server_selection_timeout: 5
  options:
    use_activesupport_time_zone: true
    use_utc: false

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://admin:password123@mongodb:27017/my_sms_dev?authSource=admin' %>
      options:
        server_selection_timeout: 5
  options:
    use_activesupport_time_zone: true
    use_utc: true

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://admin:password123@mongodb:27017/my_sms_test?authSource=admin' %>
      options:
        server_selection_timeout: 5
  options:
    use_activesupport_time_zone: true
    use_utc: false
