
development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://admin:password123@localhost:27017/my_sms_dev?authSource=admin' %>
      options:
        server_selection_timeout: 5
  options:
    # use_activesupport_time_zone: true
    use_utc: false

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://admin:password123@mongodb:27017/my_sms_dev?authSource=admin' %>
      options:
        server_selection_timeout: 30
        connect_timeout: 10
        socket_timeout: 10
        heartbeat_frequency: 10
        max_pool_size: 5
        min_pool_size: 1
  options:
    # use_activesupport_time_zone: true
    use_utc: true

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || 'mongodb://admin:password123@localhost:27017/my_sms_test?authSource=admin' %>
      options:
        server_selection_timeout: 5
  options:
    # use_activesupport_time_zone: true
    use_utc: false
